services:
  backend:
    build:
      context: .
      dockerfile: docker/back/Dockerfile
    container_name: mnist-backend
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/front/Dockerfile
    container_name: mnist-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000/api/v1/predict
    restart: unless-stopped