services:
  base:
    build:
      context: .
      dockerfile: docker/base/Dockerfile
    image: mnist-base:latest
    container_name: mnist-base

  backend:
    build:
      context: .
      dockerfile: docker/back/Dockerfile
    container_name: mnist-backend
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model
    depends_on:
      - base
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/front/Dockerfile
    container_name: mnist-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: unless-stopped